### ISSUE TITLE
fix: use separate bare repository rather than directly using the home directory

### ISSUE THREAD

**Issue by WieeRd** [WieeRd/ricefield#5]
## Current Setup

I ran `git init $HOME`. That's about it.
Oh, and I intentionally chose manual whitelisting with `.gitignore` over `status.showUntrackedFiles`.
It can avoid accidentally adding unwanted files and `git status` will still show untracked config files.

## Problem

The home directory appears as a Git repository.
It's because it is, but it causes some shenanigans like these:

- Starship prompt shows `on master` at all times, even though I'm not inside an actual project.
- My Neovim config auto save/load sessions for Git repositories. I don't want home dir session.
- Everything except dotfiles has been `.gitignore`'d, including my `~/Code/` project dir.
  - `fd`, `rg` and `eza` are blinded by this and forces me to use explicit no ignore flags

## Solution

<https://news.ycombinator.com/item?id=11070797>

Rename `.git/` to something else so that it is no longer recognized as a Git respository.

```sh
# on a fresh setup with empty $HOME
git clone $REPO --git-dir=~/.ricefield.git --work-tree=~/

# not $HOME alone
git clone --bare $REPO ~/.ricefield.git

# from existing setup
mv ~/.git ~/.ricefield.git
```

After that, $HOME will appear as a normal directory by default.
When I need to run Git operations, I can use either:

- CLI flags: `git --git-dir=~/.ricefield.git --work-tree=~/`
- Environment variables: `GIT_DIR=~/.ricefield.git GIT_WORK_TREE=~/ git`

For Git itself, I can just setup an alias, but I also need to use Neovim and Lazygit.
Some sort of virtualenv-ish command to enter and leave dotfiles editing mode will be needed

## Tasks

- [x] Rename `.git/` and test deployment
- [ ] Document bare repository setup in README
- [x] Add `dots` command to Nushell
  - `env` alias or overlay activation, maybe both
- [ ] Add `.envrc` to `~/.config`

**Comment by WieeRd** [comment]
## Ideas

- `alias dots = env GIT_DIR=~/.ricefield.git GIT_WORK_TREE=~/`
- `~/.config/.envrc`
